version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    ports:
      - "4533:4533"
    volumes:
    environment:
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_SCANSCHEDULE: 1h
    volumes:
      - "/etc/navidrome/data:/data"
      - "/etc/navidrome/music:/music:ro"
